resources:
- ../base
- env-ops-configmap.yaml
- r821cd1d/configmap.yaml

patches:
- path: traffic-routing.yaml
  target:
    kind: Service
- path: r821cd1d/revision-patch.yaml
  target:
    kind: Service
- path: r821cd1d/routing-patch.yaml
  target:
    kind: Service